runtime: python37
env: flex
entrypoint: gunicorn -b :$PORT main:app

# Specify the number of instances to use
instance_class: F1
automatic_scaling:
  min_instances: 1
  max_instances: 1

# Specify the resources that each instance should have
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
